"""initial schema

Revision ID: b6079e21b7a4
Revises: 
Create Date: 2026-06-21 21:31:55.841311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b6079e21b7a4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched', sa.Integer(), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunities',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('organization', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('apply_url', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('country', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('salary', sa.Text(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('search_tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple', coalesce(title,'') || ' ' || coalesce(organization,'') || ' ' || coalesce(location,'') || ' ' || coalesce(category,''))", persisted=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_source_external')
    )
    op.create_index('ix_opp_active', 'opportunities', ['is_active'], unique=False)
    op.create_index('ix_opp_country', 'opportunities', ['country'], unique=False)
    op.create_index('ix_opp_deadline', 'opportunities', ['deadline'], unique=False)
    op.create_index('ix_opp_posted_at', 'opportunities', [sa.literal_column('posted_at DESC')], unique=False)
    op.create_index('ix_opp_search', 'opportunities', ['search_tsv'], unique=False, postgresql_using='gin')
    op.create_index('ix_opp_tags', 'opportunities', ['tags'], unique=False, postgresql_using='gin')
    op.create_index('ix_opp_type', 'opportunities', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_opp_type', table_name='opportunities')
    op.drop_index('ix_opp_tags', table_name='opportunities', postgresql_using='gin')
    op.drop_index('ix_opp_search', table_name='opportunities', postgresql_using='gin')
    op.drop_index('ix_opp_posted_at', table_name='opportunities')
    op.drop_index('ix_opp_deadline', table_name='opportunities')
    op.drop_index('ix_opp_country', table_name='opportunities')
    op.drop_index('ix_opp_active', table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_table('ingestion_runs')
    # ### end Alembic commands ###
