"""add_recommendation_cache_to_users

Revision ID: b8a5f7d3ba1c
Revises: 99d07f5b3708
Create Date: 2026-07-04 00:10:36.791135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b8a5f7d3ba1c'
down_revision: Union[str, None] = '99d07f5b3708'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cached_recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('users', sa.Column('recommendations_cached_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'recommendations_cached_at')
    op.drop_column('users', 'cached_recommendations')
    # ### end Alembic commands ###
